# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [13]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [14]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [15]:
arreglo = arreglo + 1

In [16]:
arreglo

array([1, 2, 3, 4, 5, 6])

2. Elevar al cuadrado todos los elementos

In [17]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [18]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

3. Sumar todos los elementos

In [19]:
print(arreglo)
print(arreglo.sum())
print(lista)
print(lista.sum())

[1 2 3 4 5 6]
21
[0, 1, 2, 3, 4, 5]


AttributeError: 'list' object has no attribute 'sum'

In [20]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [21]:
arreglo.shape

(6,)

In [22]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [23]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [24]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [25]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [26]:
print('Arreglo de (1,n)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")


Arreglo de (1,n)
[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [27]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [28]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [29]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [30]:
a3 = a1 * a2
a3.shape

(2, 4)

In [31]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [32]:
arr2a = np.arange(10)
arr2a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2b = np.linspace(0,9,100)
print(arr2b.shape)
arr2b

(100,)


array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [34]:
arr3 = np.arange(10,101,dtype=int)
# mascara = (arr3 % 3 == 0)
arr3 [(arr3 % 3 == 0)]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [35]:
arr4 = np.zeros((5,10))
arr4[(1,3),:] = 1 
arr4[:,[2,7]] = 2
arr4

array([[0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.],
       [1., 1., 2., 1., 1., 1., 1., 2., 1., 1.],
       [0., 0., 2., 0., 0., 0., 0., 2., 0., 0.]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [24]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[113.87814791, 159.35584095, 121.54201384],
        [178.4866491 , 112.76690713, 105.62903199]],

       [[162.83169705, 114.62730912, 162.75071528],
        [100.10136711, 102.44440581, 162.85405206]],

       [[133.43830607, 114.03333511, 177.55830203],
        [101.97093553, 116.07740455, 130.60419618]],

       [[194.57709957, 170.74009302, 147.03892673],
        [194.98471799, 162.03523755, 169.02504504]]])

In [36]:
a = np.random.random((4,4))

In [37]:
a

array([[0.40452372, 0.43335521, 0.89036824, 0.32235984],
       [0.93397855, 0.95342102, 0.33787802, 0.74045715],
       [0.6617332 , 0.29381403, 0.84077438, 0.79363679],
       [0.41270279, 0.35797473, 0.76906351, 0.63462209]])

In [97]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [80]:
a.sum()

519

In [39]:
a.std()

23.924904214367643

In [98]:
a0 = a.copy()
a0.sort(axis=0)
a1 = a.copy()
a1.sort(axis=1)
print(a)
print(a0)
print(a1)

[[ 10 -56  30  45   5  50]
 [  5  20  30  40  50   0]
 [  5  20  30  40  50   0]
 [  5  20  30  40  50   0]]
[[  5 -56  30  40   5   0]
 [  5  20  30  40  50   0]
 [  5  20  30  40  50   0]
 [ 10  20  30  45  50  50]]
[[-56   5  10  30  45  50]
 [  0   5  20  30  40  50]
 [  0   5  20  30  40  50]
 [  0   5  20  30  40  50]]


In [83]:
a[1:3,0:3]

array([[ 5, 20, 30],
       [ 5, 20, 30]], dtype=int8)

In [59]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [84]:
a = np.array([l])

In [93]:
print(a.shape)
print(a.ndim)


(4, 6)
2


In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]])
print(a) 

[[1 2 3 4 5 6]]


In [34]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
c = a * b 
print(c) 

[[91]]


In [36]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [10]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1,'\n',arr2)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


In [19]:
# arrcon1 = np.concatenate((arr1, arr2), axis=1)
# print(arrcon1,arrcon1.shape)
# arrhsta = np.hstack((arr1, arr2))
# print(arrhsta,arrhsta.shape)
# arrcon0 = np.concatenate((arr1, arr2), axis=0)
# print(arrcon0,arrcon0.shape)
# arrvsta = np.vstack((arr1, arr2))
# print(arrvsta,arrvsta.shape)
arrsta1 = np.stack((arr1, arr2), axis=1)
print(arrsta1,arrsta1.shape)
for idx, x in np.ndenumerate(arrsta1):
    print(idx, x)
arrsta0 = np.stack((arr1, arr2), axis=0)
print(arrsta0,arrsta0.shape)
for idx, x in np.ndenumerate(arrsta0):
    print(idx, x)
arrdsta = np.dstack((arr1, arr2))
print(arrdsta,arrdsta.shape)
for idx, x in np.ndenumerate(arrdsta):
    print(idx, x)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 5
(0, 1, 1) 6
(1, 0, 0) 3
(1, 0, 1) 4
(1, 1, 0) 7
(1, 1, 1) 8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)
(0, 0, 0) 1
(0, 0, 1) 5
(0, 1, 0) 2
(0, 1, 1) 6
(1, 0, 0) 3
(1, 0, 1) 7
(1, 1, 0) 4
(1, 1, 1) 8
